name: CI tests
on:
  - push
  - pull_request

jobs:
  pre-commit:
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.18.x
        os:
          - ubuntu-20.04
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Setup dependencies
      run: |
        sudo apt install libefivar-dev libefiboot-dev python3-pip golint
        pip3 install pre-commit

    - name: Run pre-commit
      run: |
        go get .
        ~/.local/bin/pre-commit run -a

    - name: Coverage
      run: go test -v -coverprofile=profile.cov ./...

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
